learningObjectives:
  - html/semantics
  - css/selectors
  - css/flexbox
  - dom/selectors
  - dom/events
  - dom/manipulation
  - js/data-types/arrays
  - js/data-types/objects
  - js/variables
  - js/conditionals/if-else
  - js/conditionals/switch
  - js/conditionals/ternary-op
  - js/loops
  - js/functions/params
  - js/functions/args
  - js/functions/return
  - js/testing/unit
  - js/modules/es-modules
  - js/linting
  - js/semantics
  - js/expression-vs-statement
  - scm/git/clone
  - scm/git/add
  - scm/git/commit
  - scm/git/status
  - scm/git/push
  - scm/git/pull
  - scm/git/branch
  - scm/git/checkout
  - scm/git/remote
  - scm/git/fetch
  - scm/git/merge
  - scm/github/fork
  - scm/github/gh-pages
  - scm/github/pull-requests
  - scm/github/code-review
  - ux/user-understanding
  - ux/prototyping
  - ux/visual-design
  - ux/usability-testing
