learningObjectives:
  - html/semantics
  - css/selectors
  - dom/selectors
  - dom/events
  - dom/manipulation
  - js/data-types/strings
  - js/variables
  - js/conditionals/if-else
  - js/conditionals/switch
  - js/conditionals/ternary-op
  - js/loops
  - js/functions/params
  - js/functions/args
  - js/functions/return
  - js/testing/unit
  - js/modules/es-modules
  - js/linting
  - js/semantics
  - scm/git/clone
  - scm/git/add
  - scm/git/commit
  - scm/git/status
  - scm/git/push
  - scm/git/pull
  - scm/github/fork
  - scm/github/gh-pages
  - ux/user-understanding
  - ux/prototyping
  - ux/visual-design
